CREATE DATABASE onebus;

CREATE TABLE T_USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T_ONIBUS (
    ONI_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    ONI_MODELO VARCHAR(100) NOT NULL,
    ONI_PLACA VARCHAR(30) UNIQUE NOT NULL,
    ONI_CHASSI VARCHAR(30) UNIQUE NOT NULL,
    ONI_ID_APLICATIVO VARCHAR(30) UNIQUE NOT NULL,
    ONI_CAPACIDADE INT
);

CREATE TABLE T_VIAGEM (
    VIA_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    TRA_CODIGO INT NOT NULL,
    MOT_CODIGO INT NOT NULL,
    ONI_CODIGO INT NOT NULL,
    VIA_HORARIO_INICIO DATETIME,
    VIA_HORARIO_FINAL DATETIME,
    VIA_FINALIZADA BOOL,
    FOREIGN KEY (TRA_CODIGO) REFERENCES T_TRAJETO(TRA_CODIGO),
    FOREIGN KEY (MOT_CODIGO) REFERENCES T_MOTORISTA(MOT_CODIGO),
    FOREIGN KEY (ONI_CODIGO) REFERENCES T_ONIBUS(ONI_CODIGO)
);

CREATE TABLE T_HORARIOS_TRAJETO (
    HORARIO_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    TRA_CODIGO INT NOT NULL,
    HORARIO DATETIME NOT NULL,
    FOREIGN KEY (TRA_CODIGO) REFERENCES T_TRAJETO(TRA_CODIGO),
    UNIQUE (TRA_CODIGO, HORARIO)  -- Para evitar horários duplicados para o mesmo trajeto
);


CREATE TABLE T_TRAJETO (
    TRA_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    TRA_DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE T_PONTOS (
    PON_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    PON_DESCRICAO VARCHAR(100) NOT NULL,
    PON_LATITUDE DECIMAL(9, 6) NOT NULL,
    PON_LONGITUDE DECIMAL(9, 6) NOT NULL
);

CREATE TABLE T_PONTOS_TRAJETO (
    PTR_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    PON_CODIGO INT NOT NULL,
    TRA_CODIGO INT NOT NULL,
    PTR_ORDEM INT,

    FOREIGN KEY (PON_CODIGO) REFERENCES T_PONTOS(PON_CODIGO),
    FOREIGN KEY (TRA_CODIGO) REFERENCES T_TRAJETO(TRA_CODIGO),
    UNIQUE (PON_CODIGO, TRA_CODIGO)
);

CREATE TABLE T_MOTORISTA (
    MOT_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(100) NOT NULL
);