CREATE TABLE ONIBUS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MOTORISTA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    PLACA VARCHAR(30) UNIQUE NOT NULL,
    CHASSI VARCHAR(30) UNIQUE NOT NULL,
    APLICATIVO VARCHAR(30) UNIQUE NOT NULL,
    TRAJETOS_ID INT,
    CAPACIDADE INT,
    FOREIGN KEY (TRAJETOS_ID) REFERENCES TRAJETOS(ID)
);

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRAJETOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    NOME_ROTA VARCHAR(100) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE PARADA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROTA_ID INT,
    NOME_PARADA VARCHAR(100),
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    ORDEM INT,
    FOREIGN KEY (ROTA_ID) REFERENCES TRAJETOS(ID)
);

CREATE TABLE LOCALIZACOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE RECOMENDACOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    TIPO_RECOMENDACAO VARCHAR(100),
    DESCRICAO TEXT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);
